# Generated by Django 5.1.4 on 2024-12-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('DEVELOPER', 'Developer'), ('HR', 'HR'), ('MANAGER', 'Manager'), ('ADMIN', 'Admin'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=15),
        ),
    ]
